# Docs: https://taskfile.dev/#/usage
version: "3"

dotenv:
  - .env

tasks:
  format:
    cmds:
      - go tool gofumpt -l -w .

  lint:
    cmds:
      - go tool golangci-lint run --fix ./...

  generate:
    aliases:
      - gen
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test ./...

  test:clean:
    cmds:
      - go clean -testcache
      - task: test

  build:
    cmds:
      - |
        go build -v -o ./bin/avisavi \
          -ldflags "-X github.com/ahobsonsayers/avisavi/pkg/gavios/auth.defaultClientID=$AVIOS_AUTH_CLIENT_ID" \
          ./cmd/avisavi

  run:
    cmds:
      - go run ./cmd/avisavi {{.CLI_ARGS}}
